### PR TITLE
Fixes to allow: tiny method headers (with Test); locals by ref (with Test) and pinned (with Test).

### PR DESCRIPTION
**Pull request by LDj3SNuD**

### CODE REVIEW

**Comment by LDj3SNuD** [comment]
Rebased and fixed merge conflicts.

**Comment by vermorel** [comment]
Thanks a lot! I am still merging the work of @toptensoftware. I will having a look at your work soon.

**Comment by LDj3SNuD** [comment]
Fixed merge conflict.

**Comment by vermorel** [comment]
Thanks a lot for the follow-up! I am still struggling with this PR. Could you organize the commits so that they are whole, one commit at time? Indeed, there is a series of commits with one commit per file, but the changes are not isolated, so some commits are actually dependent on one another.

For example:

* one commit for the tiny method headers (ideally with test)
* one commit for the locals by ref with tests
* one for pinned locals (ideally with test)

Sorry for burdening you with this work. Your support is highly appreciated.

**Comment by LDj3SNuD** [comment]
That should be enough, sorry for single file commits.

**Comment by vermorel** [comment]
Thanks again! This PR has been merged.

**Pull request closed without merging**
