### PR TITLE
Lookup underlying FieldDefs and MethodDefs when dealing with generic constructed stuff

### LINKED ISSUE #150: Unable to look up MethodDefinition for constructed generic method
In `Lokad.ILPack.Metadata.AssemblyMetadata.TryGetMethodDefinition`, if passed a `MethodInfo` representing a constructed generic method on a non-generic type, the following sequence occurs.

1.  `if (methodInfo.DeclaringType.IsConstructedGenericType)` is false.  The type is not generic.
2. `_methodDefHandles.TryGetValue(methodInfo, out metadata)` returns false, because the cache contains the generic method definition

(A similar problem exists on `TryGetFieldDefinition` for fields on constructed generic types.)

### PR DESCRIPTION
**Pull request by masonwheeler**
Fixes #150

### CODE REVIEW

**Comment by vermorel** [comment]
This contribution looks quite good. It seems you are fixing a long-standing HACK of mine. However, it's lacking a test. 

@masonwheeler  Could you update `TestSubject` project with an extra example that illustrates a case that would fail otherwise?

**Comment by masonwheeler** [comment]
It's not clear how `TestSubject` works or how to add to it.  My test source is [the test corpus of an actual compiler that uses refemit as its codegen.](https://github.com/boo-lang/boo/tree/master/tests).

Because this deals with defs rather than refs, the proper way to test this would be:

1) Create a generic type `A<T>`.
2) Create a non-generic type `B`.
3) Put a field of type `A<int>` on `B`.
4) Put a generic method on `B`.

How should a test like that be set up?

**Comment by vermorel** [comment]
You create a file in `TestSubject`  for example `MethodWithSZArray()` in https://github.com/Lokad/ILPack/blob/master/test/TestSubject/MyClass.Arrays.cs and then you create the corresponding test behavior, for example `MethodWithSZArray()` in https://github.com/Lokad/ILPack/blob/master/test/Lokad.ILPack.Tests/RewriteTest.Arrays.cs 

Hope it helps. Cheers, Joannes

**Comment by masonwheeler** [comment]
OK, just added tests.  I'm not able to verify them, though, as none of ILPack's tests run successfully on my system.  Every last one fails with a message similar to the following:

>      System.TypeInitializationException : The type initializer for 'Lokad.ILPack.Tests.RewriteTest' threw an exception.
> ---- System.IO.FileNotFoundException : Could not load file or assembly 'netstandard' or one of its dependencies. The system cannot find the file specified.
> 
>   Stack Trace: 
> RewriteTest.ctor()
> ----- Inner Stack Trace -----
> RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
> RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
> RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
> RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
> RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
> Assembly.Load(String assemblyString)
>

**Comment by masonwheeler** [comment]
Nevermind; that was the 4.6 version, likely because I don't have the .NET Framework 4.6 SDK installed.  The netstandard tests appear to run correctly.

**Comment by masonwheeler** [comment]
Have you been able to test and verify this?

**Review by vermorel — APPROVED** [review]

**Comment by vermorel** [comment]
@masonwheeler Your commits have been squashed and merged. Thanks again for this contribution.

**Pull request closed without merging**
